DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS buyers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS favourite_items CASCADE;
DROP TABLE IF EXISTS order_history CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;


CREATE TABLE sellers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE buyers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES sellers(id) ON DELETE CASCADE,
  price INTEGER NOT NULL DEFAULT 0,
  availability BOOLEAN NOT NULL DEFAULT TRUE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  thumbnail_image_url VARCHAR(255) NOT NULL,
  product_image_url VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  type TEXT,
  material VARCHAR(255),
  size VARCHAR(255)

);

CREATE TABLE favourite_items (
  id SERIAL PRIMARY KEY NOT NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  buyer_id  INTEGER REFERENCES buyers(id) ON DELETE CASCADE

);

CREATE TABLE order_history (
  id SERIAL PRIMARY KEY NOT NULL,
  buyer_id INTEGER REFERENCES buyers(id) ON DELETE CASCADE,
  total_cost INTEGER NOT NULL DEFAULT 0

);


CREATE TABLE order_items (
  id SERIAL PRIMARY KEY NOT NULL,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  quantity SMALLINT NOT NULL DEFAULT 0,
  cost INTEGER NOT NULL DEFAULT 0,
  order_id INTEGER REFERENCES order_history(id) ON DELETE CASCADE

);


