DROP TABLE IF EXISTS order_history CASCADE;

CREATE TABLE order_history (
  id SERIAL PRIMARY KEY NOT NULL,
  buyer_id INTEGER REFERENCES buyers(id) ON DELETE CASCADE,
  total_cost INTEGER NOT NULL DEFAULT 0
);
